[profile.default]
src = "contracts"
test = "test"
script = "script"
libs = ["lib"]
solc_version = "0.8.24"
optimizer = true
optimizer_runs = 10000
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
tipschain = "${RPC_URL}"

[fuzz]
runs = 256

[invariant]
runs = 128
depth = 64
